//HintName: SignalRBridgeGenerator.g.cs
// <auto-generated />
// 1 hub found


/*
    namespace Test
    {
        public partial class TestHub
        {
            public static class ToClient
            {
                /// <summary>
                /// <see cref="SayHello"> is derived from 
                /// <see cref="global::Test.ITestClient.SayHello(global::System.String)"></summary>
                public record SayHello(global::System.String Name);
            }
            
            public static class ToServer
            {
                /// <summary>
                /// <see cref="SayBye"> is derived from 
                /// <see cref="global::Test.ITestServer.SayBye(global::System.String)"></summary>
                public record SayBye(global::System.String Name);
            }
        }
    }
*/
